### ISSUE TITLE
Containers created with CLI not showing

### ISSUE THREAD

**Issue by klinden** [docker/kitematic#1932] opened 2016-08-24 16:07 UTC
### Expected behavior
After creating a container with the Docker CLI it should show in the list of containers running on the machine
### Actual behavior
The container does not show in the list unless the application is force quit and restarted

### Steps to reproduce the behavior

  1. Create a container with the Docker CLI (i.e. docker run....)
  2. Note that the container doesn't show in the list of containers
  3. Restart Kitematic
  4. The container shows in the list

**Comment by FrenchBen** [comment] 2016-08-26 01:46
We did add a 'Refresh Container List' option to the view; if this happens again, you can refresh the list, which usually fixes this.

**Comment by FrenchBen** [comment] 2016-08-26 01:46
closing as duplicate of #1893

**Closed by FrenchBen** 2016-08-26 01:46 UTC

**Comment by Salseiro** [comment] 2017-03-25 16:01
Hey, just a brief follow-up: a container I created in Native mode is not shown whenever I choose to run Kitematic in VirtualBox mode. Why is that an issue?

**Comment by FrenchBen** [comment] 2017-03-27 18:00
Because native and Vbox containers aren't shared.
