### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by NormanColoma** [docker/kitematic#4094] opened 2018-09-07 09:48 UTC
### Expected behavior

After login, loggged in successfully

### Actual behavior

Login page remains hanging after login

### Information about the Issue

Once you click login button, login page remains hanging with the spinning.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pablomirallessoler** [comment] 2018-09-10 07:31
I have the same problem on mac os

**Comment by ajustlike** [comment] 2018-09-10 07:54
win7 the same problem

**Comment by mpash** [comment] 2018-09-11 00:49
I'm getting it as well. I'm able to login via the CLI, and the system tray app, but Kitematic hangs after attemping a login.

**Comment by wesgtr** [comment] 2018-09-11 16:49
I'm with the same problem, in Windows 10. I have installed right now, and trying to login get this error, but the login data, and still loading forever.
![screen shot 2018-09-11 at 13 48 19](https://user-images.githubusercontent.com/41586568/45374776-7e7d6080-b5c9-11e8-8eb4-3e86631070dc.png)

**Comment by israelpereira** [comment] 2018-09-12 12:46
Same here, Windows 10 Pro

**Comment by nbortolotti** [comment] 2018-09-12 18:27
same here, ubuntu 18.04.01 LTS, kitematic 0.17.03

**Comment by jaypozo** [comment] 2018-09-14 04:07
Same issue, Ubuntu 16.04

**Comment by owen800q** [comment] 2018-09-14 08:28
I have the same issue on ubuntu 16.04 .....

**Comment by BorisBerlin** [comment] 2018-09-14 17:41
Same in Win10

**Comment by bhargodevarya** [comment] 2018-09-14 18:48
Same here as well, windows 7 enterprise

**Comment by Ubaid-Gul** [comment] 2019-06-23 06:53
No solution is provided anywhere except duplicate duplicate.

**Comment by alexwasner** [comment] 2019-09-19 19:04
A year old issue with something as important as logging in and there is no solution or update anywhere. Fantastic.

**Comment by timmay54** [comment] 2019-09-19 19:21
@alexwasner I feel ya. same issue

**Comment by AnthonyFuscoSE** [comment] 2019-09-19 19:52
Same issue

**Comment by quickware** [comment] 2019-09-20 14:31
same issue with Kitematic-0.17.8-Windows.zip on windows 10

**Comment by anthony0030** [comment] 2019-09-20 15:26
Same issue with Kitematic 0.17.6 on OSX

**Comment by manowark** [comment] 2019-09-21 08:25
Same issue 
- Kitematic 0.17.6
- macOS 10.14.6

**Comment by grimwinoleader** [comment] 2019-09-21 18:03
Same issue for me too:
- Docker Desktop 2.1.0.3
- Kitematic 0.17.8
- macOS 10

14.6

**Comment by tobarsegais** [comment] 2019-09-24 05:25
Same issue for me:
Was annoying because Docker insisted I upgrade to the latest version of Kitematic.

- Docker Desktop 2.1.0.3
- Kitematic 0.17.8
- macOS 10.14.6

**Comment by rizkiherda** [comment] 2019-09-24 20:05
Same here, Windows 10 Pro

**Comment by gwc4github** [comment] 2019-09-26 17:42
This is still an issue but there is a fix you can get here: https://github.com/docker/kitematic/issues/5308

**Comment by UnMatty** [comment] 2019-09-29 17:34
same problem on MacOs 10.14.6

**Comment by MySource14** [comment] 2019-09-30 07:32
Same issue too on win 10 pro.

**Comment by Raizelian** [comment] 2019-09-30 15:52
Same issue with:
- macOS 10.14.6
- Kitematic 0.17.8
- Docker 2.1.0.3

But I can confirm that this fix works perfectly:
> (https://github.com/docker/kitematic/issues/4094#issuecomment-535612310) This is still an issue but there is a fix you can get here: #5308

**Comment by stephen-turner** [comment] 2019-09-30 17:34
Thanks for the report. There was a change in the Hub login API code a few days ago, and we accidentally lost a backward compatibility fix. (In fact the one that we put in place when this ticket was first opened in September 2018). If possible, we're looking to re-fix it in Hub, rather than get everyone to download a new Kitematic.

**Comment by 153957** [comment] 2019-10-01 07:58
@stephen-turner Can you provide a time estimate for when this might be fixed on Docker Hub?

**Comment by ulrich** [comment] 2019-10-02 07:46
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.

**Closed by ulrich** 2019-10-02 07:46 UTC

**Comment by anthony0030** [comment] 2019-10-02 10:06
I can confirm it is working for me now and it logged in fast.
