### ISSUE TITLE
Error :(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### ISSUE THREAD

**Issue by test2301** [docker/kitematic#4267] opened 2018-11-09 12:03 UTC
### Expected behavior

While trying to create a new container from kitematic UI for elasticsearch got this 404 error.
Ideally it should create a new container.

### Actual behavior

Got an error 

(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC
