### ISSUE TITLE
enhancement: large image does not run

### ISSUE THREAD

**Issue by geoHeil** [docker/kitematic#1209] opened 2015-11-12 13:34 UTC
The large image (fluxcapacitor/pipeline, 5GB) does not seem to run with kitematic.

I can't find a possibility to set `boot2docker --memory=8192 --disksize=20000 init` to enable it to run the images.

I just saw this is a dublicate of https://github.com/kitematic/kitematic/issues/258
Strangely it does not seem to work after upgrading RAM and having a 16 GB HDD

**Comment by alexandrev** [comment] 2015-11-12 15:09
Do you have any kind of error or something to work with? Do you try to increase the settings of the VM using the Oracle Virtualbox GUI?

**Comment by geoHeil** [comment] 2015-11-12 15:11
Yes I used the Virutalbox GUI. Kitematic & docker report the container running, however the logs only show `root@f788d2564fbe: ~root@f788d2564fbe:~# exit`

**Comment by alexandrev** [comment] 2015-11-12 15:13
Are you using a public Dockerfile we can try from my side? It seems the docker container finishes...

**Comment by geoHeil** [comment] 2015-11-12 15:15
I am using https://hub.docker.com/r/fluxcapacitor/pipeline/ with `docker pull fluxcapacitor/pipeline`
This are their instructions https://github.com/fluxcapacitor/pipeline/wiki/Setup-Docker

**Comment by alexandrev** [comment] 2015-11-12 15:23
Ok, I'm going to try to reproduce your error, but I don't feel confident with the image you are using because taking a look here: https://github.com/fluxcapacitor/pipeline/blob/master/Dockerfile I don't see a CMD sentence inside the Dockerfile ... 

Taking a look of their instructions https://github.com/fluxcapacitor/pipeline/wiki/Start-Docker, it confirms the problem, because they execute the run with the bash command appended. As far as I know (I wish if @FrenchBen or some other dev could confirm thix) Kitematic doesn't allow to specify another "command" to run.

So, I think the behaviour is the expected, but I want to try it but I think I'm not be able to get back to you until later this evening.

**Comment by geoHeil** [comment] 2015-11-12 15:27
Thank you. No worries.

**Comment by FrenchBen** [comment] 2015-12-11 19:16
As explained by @alexandrev this is an issue with a lack of cmd/entry point in the Dockerfile. Unfortunately you may need to start this one from cli until a good solution is in place. 

Closing this for now.

**Closed by FrenchBen** 2015-12-11 19:16 UTC
