### ISSUE TITLE
icould not pull images from elastic.co (kibana, eleasticsearch)

### ISSUE THREAD

**Issue by ze357** [docker/kitematic#4084] opened 2018-09-03 14:06 UTC
### Expected behavior
could pull images for elasticsearch, kibana, logstash or elk. 

### Actual behavior
could not pull Images --> falls path
can't add further docker path 

right path: 
docker.elastic.co/elasticsearch/elasticsearch:6.4.0
docker.elastic.co/kibana/kibana:6.4.0

### Information about the Issue
(HTTP code 404) no such image - no such image: docker.elastic.co/elasticsearch:6.4.0: No such image: docker.elastic.co/elasticsearch:6.4.0

### Steps to reproduce the behavior

1. new 
2. search latest Image for kibana, elasticsearch, elk, logstash .....
3. create  .... 
4. see error message

**Comment by thaJeztah** [comment] 2019-02-28 10:31
Looks like those repositories d not have a `:latest` tag, so you will have to specify a specific tag to use; here's the steps to do so (steps below are for the `elasticsearch` image, but the steps are similar for other images):

<img width="288" alt="screenshot 2019-02-28 at 11 13 10" src="https://user-images.githubusercontent.com/1804568/53559259-0dffd700-3b4a-11e9-84dc-aca7eadb8266.png">

Click on the `...` button to view the image's details

<img width="289" alt="screenshot 2019-02-28 at 11 13 25" src="https://user-images.githubusercontent.com/1804568/53559322-27088800-3b4a-11e9-91ec-88ca26854d28.png">

Click on the `Selected tag: latest` to open the "tag selection" window

<img width="293" alt="screenshot 2019-02-28 at 11 13 48" src="https://user-images.githubusercontent.com/1804568/53559363-3be51b80-3b4a-11e9-8bd0-c5da16e891cd.png">

Click the tag / version of the image you want to run

<img width="296" alt="screenshot 2019-02-28 at 11 13 57" src="https://user-images.githubusercontent.com/1804568/53559412-51f2dc00-3b4a-11e9-924a-2929fafdcdbb.png">

Click the `(X)` to close the tag selector window

<img width="295" alt="screenshot 2019-02-28 at 11 14 16" src="https://user-images.githubusercontent.com/1804568/53559443-62a35200-3b4a-11e9-8691-57e375a90a7b.png">

Click on the `Create` button to pull the image and start the container

Closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-02-28 10:31 UTC
