### ISSUE TITLE
elasticsearch image not available

### ISSUE THREAD

**Issue by marcinmatias** [docker/kitematic#4378] opened 2018-12-12 09:02 UTC
### Expected behavior
to download elasticsearch image
### Actual behavior
error while download
### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for elasticsearch:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2018-12-13 12:37
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:37 UTC
