### ISSUE TITLE
After upgrade to DockerTools 1.9.0, Kitematic Containers list is empty if it starts default VM

### ISSUE THREAD

**Issue by DonPwrShellHunt** [docker/kitematic#1174] opened 2015-11-04 14:00 UTC
OS X El Capitan (Version 10.11.1)
DockerTools 1.9.0
Docker 1.9.0
docker-machine 0.5.0
VirtualBox 5.0.8

How to reproduce>
With no docker machines running, launch Kitematic.
Delay with progress indicator happens while Linux VM is starting.
Containers list is not populated.
Under Settings, uncheck "Shutdown Linux VM on closing Kitematic".
Quit Kitematic.
Confirm Linux VM is running via docker-machine ls
Launch Kitematic 
Containers list is populated in left pane immediately & works as expected

**Comment by FrenchBen** [comment] 2015-11-05 00:39
I haven't been able to reproduce this. To confirm:
```bash
$ docker-machine ls                                                                                                  
NAME      ACTIVE   DRIVER         STATE     URL   SWARM
default   -        virtualbox     Stopped
```
Started Kitematic 0.9.3 app, which showed the 'Starting Docker VM' - Once up confirmed the VM was up and running:
```bash
$ docker-machine ls
NAME      ACTIVE   DRIVER         STATE     URL   SWARM
default   -        virtualbox     Stopped
```
Also immediately saw my containers on the left hand-side. 
Went under settings to uncheck the 'Shutdown Linux VM on closing Kitematic' - Quit kitematic, verified the VM was still up and running.
Launched Kitematic and saw once again the container list populated.

**Comment by DonPwrShellHunt** [comment] 2015-11-05 04:28
Following screen shots show the two states I described in my original post.
I can reproduce on my system reliably. Are there any logs I could check to help locate root cause?

![kitematicnocontainers](https://cloud.githubusercontent.com/assets/3642348/10959814/307a03ba-834b-11e5-8c15-ed68b81c8be6.png)
![kitematicwithcontainers](https://cloud.githubusercontent.com/assets/3642348/10959815/3761adae-834b-11e5-9216-6c725940d264.png)

**Comment by FrenchBen** [comment] 2015-11-05 18:24
Can you do a similar test via a terminal to see how long the initial `docker ps` takes? Maybe there's a time-out?
There isn't much log related to this, as it's normally a straight-forward process.

**Comment by DonPwrShellHunt** [comment] 2015-11-05 23:50
It takes 27-30 seconds to start the "default" VirtualBox VM.

bash-3.2$ date;docker-machine start default;date;docker-machine ls
Thu Nov  5 18:45:07 EST 2015
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Thu Nov  5 18:45:34 EST 2015
NAME        ACTIVE   DRIVER         STATE     URL                         SWARM
default     *        virtualbox     Running   tcp://192.168.99.100:2376

**Comment by FrenchBen** [comment] 2015-11-06 00:24
`date;docker-machine start default;date;docker-machine ls;date;docker-machine ssh default docker ps;date;`
Is the one I was more interested it to see if the `docker ps` command is being delayed.
To get also some info:
`docker --version`
`docker-machine ssh default docker --version`

**Comment by DonPwrShellHunt** [comment] 2015-11-06 14:51
bash-3.2$ date;docker-machine start default;date;docker-machine ls;date;docker-machine ssh default;docker ps;date
Fri Nov  6 09:38:09 EST 2015
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Fri Nov  6 09:38:36 EST 2015
NAME        ACTIVE   DRIVER         STATE     URL                         SWARM
default     *        virtualbox     Running   tcp://192.168.99.100:2376   
                             
Fri Nov  6 09:38:36 EST 2015
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9

----------------------------------------------------
bash-3.2$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9
docker@default:~$ docker --version
Docker version 1.9.0, build 76d6bc9
docker@default:~$

**Comment by FrenchBen** [comment] 2015-11-06 19:29
The following is actually 1 command:
`docker-machine ssh default docker ps`

The idea is to time the time it takes for docker ps to respond - Can you list the images you're using so that I can set it up exactly as you have it?

**Comment by DonPwrShellHunt** [comment] 2015-11-06 20:09
OK - we may be getting to the crux of the problem. Here is the sequence when I ran your command as you had it listed>

bash-3.2$ docker-machine ls
NAME        ACTIVE   DRIVER         STATE     URL   SWARM
default     -        virtualbox     Stopped         
       
bash-3.2$ date;docker-machine start default;date;docker-machine ls;date;docker-machine ssh default docker ps;date
Fri Nov  6 09:34:04 EST 2015
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Fri Nov  6 09:34:31 EST 2015
NAME        ACTIVE   DRIVER         STATE     URL                         SWARM
default     *        virtualbox     Running   tcp://192.168.99.100:2376   
                             
Fri Nov  6 09:34:32 EST 2015
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
exit status 1
Fri Nov  6 09:34:32 EST 2015

To test the command that failed I repeated that command as two separate ones, and when it worked I figured there was a typo in the original cmd. Guess not :)

bash-3.2$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9
docker@default:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES


Current containers/images

docker@default:~$ docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                       PORTS               NAMES
3e3205697a40        donhunt124/twocent            "/bin/bash"              15 hours ago        Exited (137) 14 hours ago                        JustBash
d229f8f4216a        mazzolino/tiddlywiki:latest   "/usr/local/bin/init-"   16 hours ago        Exited (143) 5 minutes ago                       tiddlywiki
docker@default:~$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
donhunt124/twocent     latest              9d7498d56abc        21 hours ago        365.7 MB
williamyeh/ansible     centos7-onbuild     312e6b496b4a        9 days ago          236.2 MB
mazzolino/tiddlywiki   latest              29c3f4f81d96        9 months ago        367.3 MB
docker@default:~$ 

donhunt124/twocent is an image I created from centos-onbuild with a Dockerfile.

But even with just the tiddlywiki image & container, I get the same symptoms.

**Comment by DonPwrShellHunt** [comment] 2015-11-06 20:33
*OK - we may be getting to the crux of the problem. Here is the sequence when I ran your command as you had it listed>*

      bash-3.2$ docker-machine ls
      NAME        ACTIVE   DRIVER         STATE     URL   SWARM
      default     -        virtualbox     Stopped         
        
      bash-3.2$ date;docker-machine start default;date;docker-machine ls;date;docker-machine ssh default docker ps;date
      Fri Nov  6 09:34:04 EST 2015
      Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
      Fri Nov  6 09:34:31 EST 2015
      NAME        ACTIVE   DRIVER         STATE     URL                         SWARM
      default     *        virtualbox     Running   tcp://192.168.99.100:2376   
                              
      Fri Nov  6 09:34:32 EST 2015
      Cannot connect to the Docker daemon. Is the docker daemon running on this host?
      exit status 1
      Fri Nov  6 09:34:32 EST 2015
      
*Tried failed command as two distinct commands, which worked.*

      bash-3.2$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
      _                 _   ____     _            _
      | |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
      | '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
      | |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
      |_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
      Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
      Docker version 1.9.0, build 76d6bc9
      docker@default:~$ docker ps
      CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

*Current containers/images*

      docker@default:~$ docker ps -a
      CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
      3e3205697a40 donhunt124/twocent "/bin/bash" 15 hours ago Exited (137) 14 hours ago JustBash
      d229f8f4216a mazzolino/tiddlywiki:latest "/usr/local/bin/init-" 16 hours ago Exited (143) 5 minutes ago tiddlywiki
      docker@default:~$ docker images
      REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
      donhunt124/twocent latest 9d7498d56abc 21 hours ago 365.7 MB
      williamyeh/ansible centos7-onbuild 312e6b496b4a 9 days ago 236.2 MB
      mazzolino/tiddlywiki latest 29c3f4f81d96 9 months ago 367.3 MB
      docker@default:~$

donhunt124/twocent is an image I created from centos-onbuild with a Dockerfile.

But even with just the tiddlywiki image & container, I get the same symptoms.

**Comment by FrenchBen** [comment] 2015-11-06 21:56
Interesting, the previous command works full on my Mac no problem, but perhaps it's running it as 2 commands for you? No matter what we spin up the VM and then actually get the data. 
Out of curiosity, what do you get with:
`docker-machine ssh default docker info`

**Comment by DonPwrShellHunt** [comment] 2015-11-06 22:16
It appears to be a timing issue, since that command fails when the 
default VM has just been started, but the same command works later.
I'm not sure how much time = later.

    bash-3.2$ docker-machine ssh default docker info
    Containers: 2
    Images: 31
    Server Version: 1.9.0
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 35
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.12-boot2docker
    Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
    CPUs: 1
    Total Memory: 1.956 GiB
    Name: default
    ID: J7S3:MDWB:VOZ4:DXAT:LVWB:7LRZ:RZNR:7QEI:G6BL:WUQA:XNDC:WBT3
    Debug mode (server): true
     File Descriptors: 18
     Goroutines: 30
     System Time: 2015-11-06T22:06:32.467748543Z
     EventsListeners: 1
     Init SHA1: 
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

And here is the same command that failed, but now works.

    bash-3.2$ docker-machine ssh default docker ps
    CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                     NAMES
    d229f8f4216a        mazzolino/tiddlywiki:latest   "/usr/local/bin/init-"   24 hours ago        Up 6 hours          0.0.0.0:32768->8080/tcp   tiddlywiki

**Comment by FrenchBen** [comment] 2015-11-06 22:27
Interesting....
One way to maybe pin-point this, is to keep the VirtualBox.app window open and see from the preview where the machine really is compared to maybe what's reported in the terminal.

I have no clue why would you have such delays, as it's not something I've been able to replicate.

**Comment by DonPwrShellHunt** [comment] 2015-11-06 23:24
Here are a couple of console screen shots that show most of what is happening as the vm comes up.
It took multiple runs to capture them, so don't interprete them as one.

![dockerdefault_1st](https://cloud.githubusercontent.com/assets/3642348/11011099/d4a78e4a-84b2-11e5-9c7a-8fb61c1067f0.png)

Segmentation fault does not look normal in above image.

![dockerdefault_2nd](https://cloud.githubusercontent.com/assets/3642348/11011108/e631aaa6-84b2-11e5-8fef-df67ab2813c0.png)


The default VM is in the process of setting up networking when the command fails. Immediately after the networking is set up, the Need TLS certs line is output to the console, followed by the remainder shown in the image below.

![dockerdefault](https://cloud.githubusercontent.com/assets/3642348/11010769/8f1ccfb4-84af-11e5-9212-04e9629f58c0.png)

**Comment by FrenchBen** [comment] 2015-11-06 23:29
Sounds like it's the source of your problem. Even though the VM is 'up/started' it doesn't look like network is setup till afterwards, preventing Kitematic from displaying the containers.

If your VM can be discarded, it'd be interesting to see if removing it and re-creating it solves this.
`docker-machine stop default`
`docker-machine rm default`
Then open the VirtualBox app and under 'VirtualBox > Preference' menu, select 'Network' then 'Host-Only Networks'. 
![host-only network](https://cloud.githubusercontent.com/assets/3965324/11011266/20627114-849b-11e5-9d95-e69403587306.png)


Delete all Host-Only network interface that have been created, then re-launch Kitematic to have it setup the new default VM and associated network interface.

**Comment by DonPwrShellHunt** [comment] 2015-11-07 17:28
Removing and recreating the default VirtualBox VM did not fix my symptoms.

FYI - Here is the type of system I'm running on>
iMac (27-inch, Late 2013), 3.5 GHz Intel Core i7, 24 GB 1600 MHz DDR3, NVIDIA GeForce GTX 775M 2048 MB

**Comment by FrenchBen** [comment] 2015-11-09 18:42
@DonPwrShellHunt Did you make sure to remove ALL network adapters as shown above?
May need to remove all then restart.

**Comment by DonPwrShellHunt** [comment] 2015-11-09 19:22
Yes, I removed ALL the Host-only Networks (there were two), closed VirtualBox, and launched Kitematic - where it proceeded to create the default VirtualBox VM from scratch.

Based on the symptoms, the question that comes to my mind is> Isn't there a way for docker-machine to determine that the VM is not only "running" but also active on the network? Should an issue to this effect be created against docker-machine?

**Comment by FrenchBen** [comment] 2015-11-09 19:42
Both are checked - The delay you are experiencing is the first one I've seen. 
Are you on an internal network that has an IP similar to the VM's IP? Causing maybe some light delays when trying to find the VM? (just throwing things out there)

It would be useful to know any/all details of your current setup to determine what could be causing it. 
For example if you were to go down to your nearest Starbucks do you experience the same thing?

**Comment by DonPwrShellHunt** [comment] 2015-11-10 14:23
The class C subnet where the default VirtualBox VM is created is not used for any other devices.
```
Dons-iMac:~ donhunt$ netstat -r | grep vbox
192.168.99         link#11            UC              4        0 vboxnet
192.168.99.100     8:0:27:83:b3:bc    UHLWIi          4     1628 vboxnet   1187
192.168.99.255     link#11            UHLWbI          1      181 vboxnet
```

Since this is a 27-inch iMac, I have not tried taking it to Starbucks...

I do not use wireless networking on this machine, it is directly wired to a switch, and has an IP in the class C 192.168.1.x subnet. And I've not observed any odd behavior connecting using `docker-machine ssh default` once it does come up completely.

The tiddlywiki container also runs fine.

**Comment by kidhasmoxy** [comment] 2015-12-01 20:54
We have several users that have reported a similar issue on different versions of OS X, with the latest Kitematic install from the Docker Toolbox (myself included.) The fix that seems to work best is to disable the option that tells Kitematic to shutdown the VM when quiting, then just restarting Kitematic. 

It seems to happen most often when Kitematic is starting the VM, but a quick relaunch fixes it for most. Some users have just taken to using the Quickstart terminal, since the Containers show up just fine there.

**Comment by FrenchBen** [comment] 2015-12-01 23:40
From the above it seems that the Virtualbox layer is becoming the bottleneck. I usually disable the VM shutdown as well and rarely see the same lag. 

I'll keep this open to come back to.

**Closed** 2016-04-13 01:28 UTC
