### ISSUE TITLE
Elasticsearch setup error

### ISSUE THREAD

**Issue by gitpubz** [docker/kitematic#4242] opened 2018-11-01 16:49 UTC
### Information about the Issue - (HTTP code 404) unexpected - manifest for jhbhatt/elasticsearch-6.4.2:latest not found

<img width="1003" alt="screen shot 2018-11-01 at 12 49 02 pm" src="https://user-images.githubusercontent.com/43648497/47866240-95278300-ddd4-11e8-85ec-b827cde36543.png">

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC
