### ISSUE TITLE
OS X user interface via Apple Screen Sharing extremely slow when docker container is running 

### ISSUE THREAD

**Issue by APMOadmin** [docker/kitematic#1689] opened 2016-05-21 01:08 UTC
### Expected behavior
user interface response does not change whether docker container is running or not

### Actual behavior
user interface response via apple remote desktop extremely slow when docker container is running (overall CPU usage < 10%). 

### Information about the Issue
OS X 10.11.5
- Apple Apple screen sharing (VNC)
`This seams to be the case with apple screen sharing (VNC) only. When accessing server via e.g. TeamViewer UI response does not change whether a docker container is running or not
`- Docker Version 1.11.1-beta12 (build: 7528)
- UI response/performance returns to normal when container is stopped or kinematic is shut down (with container still running)

### Steps to reproduce the behavior

  1. start any docker container

**Comment by FrenchBen** [comment] 2016-05-23 19:00
Looking at the steps you provided, having any container started is causing this. I run containers 14/5 on my laptop and havent' had this issue.
You're providing some information about Apple VNC, can you be more specific about what's actually happening, exact steps to reproduce (setup VNC as server or client? install teamviewer? what exact image are you using, etc?)

**Comment by APMOadmin** [comment] 2016-05-23 23:46
The issue only appears when connected to the host via Apple Screen Sharing.
Just to be clear: the containers run fine it's just kinematic that somehow
impacts the UI response...

**Comment by FrenchBen** [comment] 2016-05-24 23:16
It's possible that some of the rendering done with Kitematic impacts the speed of refresh. 
This is unfortunately out of scope.

**Closed by FrenchBen** 2016-05-24 23:16 UTC

**Comment by APMOadmin** [comment] 2016-05-24 23:51
What exactly do you mean with "out of scope" - docker builds a user interface for OS X that is not usable in a distributed environment ? Or do I miss something here ?

**Comment by FrenchBen** [comment] 2016-05-25 01:23
Running Kitematic through an Apple VNC and mentioning that the refresh rate of the VNC is an issue with Kitematic seems to be a bit far-fetched IMHO. 

Kitematic is a desktop management tool - If you're looking for a remote management tool, there are other products that can do this for you; Docker Cloud is one of them and manages 1 node for free

**Comment by awgeorge** [comment] 2016-06-22 08:53
Just wanted to try and give some more information with this. Docker or the VM isn't an issue here, with both installed and running Apple remote desktop (ARDP) is responsive. However as soon as you launch the kitematic UI into the foreground, ARDP is literally unusable. For remote servers this isn't a great experience.

You can mitigate the problem by launching kitematic, starting / edit any configuration needed, then minimise or close the window, ARDP will be normal after it's off the screen. - But you have to be quick, the longer the UI is in the foreground, the more screwed you are.

Just because this bug is only highlighted when using ARDP or VNC clients, doesn't mean there isn't an issue when using the application locally, its probably just masking the issue.

I can record a video if that will help to debug the problem, but It looks like you are aware that your rendering is (probably) non-standard.

kitematic v0.10.4
