### ISSUE TITLE
Cannot create ElasticSearch container.

### ISSUE THREAD

**Issue by nejdetckenobi** [docker/kitematic#4209] opened 2018-10-22 14:44 UTC
### Expected behavior

Creating an ElasticSearch instance.

### Actual behavior

Getting the message: `(HTTP code 404) unexpected - manifest for elasticsearch:latest not found`

### Information about the Issue

Using VB, OSX Mojave, 
Docker version 18.03.1-ce, build 9ee9f40

### Steps to reproduce the behavior

  1. Open Kitematic
  2. Click `+ New`
  3. Find official elasticsearch (elasticsearch:latest)
  4. Click `CREATE`
  5. You'll see the error.

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC
