### ISSUE TITLE
Kitematic cannot find any local images

### ISSUE THREAD

**Issue by abhiesa** [docker/kitematic#3481] opened 2018-01-05 11:55 UTC
### Expected behavior
In my images should list local images (in my cases more than 50)
### Actual behavior
showing message: Cannot find local images
### Information about the Issue
Version 17.09.1-ce-mac42 (21090)
Channel: stable
3176a6af01

### Steps to reproduce the behavior
![screen shot 2018-01-05 at 5 23 51 pm](https://user-images.githubusercontent.com/460481/34608250-62e47462-f23d-11e7-9594-11fe9f318569.png)
![screen shot 2018-01-05 at 5 24 18 pm](https://user-images.githubusercontent.com/460481/34608253-6415e5b4-f23d-11e7-9d1a-23a79ffcbec0.png)
![screen shot 2018-01-05 at 5 24 37 pm](https://user-images.githubusercontent.com/460481/34608254-645ee0ca-f23d-11e7-9e93-5a096edfcfb3.png)

**Comment by collin5** [comment] 2018-01-05 12:34
@abhiesa I can't seem to replicate this behavior. My images show up just fine. Is it possible that this is being caused by something else?

<img width="420" alt="screen shot 2018-01-05 at 15 28 50" src="https://user-images.githubusercontent.com/11579108/34609411-b1b539e2-f22d-11e7-94fc-4fd0c513cc7b.png">

**Comment by vedydev** [comment] 2018-01-08 14:13
Facing the same issue on macOS with docker toolbox.
Created a new container, run it, stopped it
Can't find it to run it again.
How to locate and run the contained I have created again?

**Comment by korykim** [comment] 2018-02-07 00:30
@abhiesa I'm the same question as you.

**Comment by FrenchBen** [comment] 2018-02-07 10:08
@vedydev @korykim please provide actual steps to replicate. 
Closing until steps are provided.

**Closed by FrenchBen** 2018-02-07 10:08 UTC

**Comment by icalphil** [comment] 2018-08-26 05:01
In the setting, try uncheck "Use VirtualBox instead of Native on next restart", this resolve the issue where I was not able to find any local image or container that was created.

**Comment by techarkio** [comment] 2018-09-23 03:18
> In the setting, try uncheck "Use VirtualBox instead of Native on next restart", this resolve the issue where I was not able to find any local image or container that was created.

In kitematic, uncheck the option resolved my problem.

**Comment by lilijialiang** [comment] 2018-11-08 06:35
I'm the same question.

macos 10.14

**Comment by bryan-lunt** [comment] 2019-01-07 21:23
The same thing. I am using native.
There is an unhandled exception in the Kitematic Javascript. I think because it expected lower level code to always return a list of containers?

> [Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252 Uncaught TypeError: Cannot read property 'includes' of undefined
    at /Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252:24
    at Array.filter (native)
    at Constructor.render (/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:251:40)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.mountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent._createContentMarkup (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)

**Comment by muhammadkounta** [comment] 2019-02-06 23:52
1: Go to Kitematic > Preferences
2: Uncheck `Use VirtualBox instead of Native on next restart`
3: Close Kitematic
4: Restart Docker
5: Open Kitematic (all local images will be visible)

**Comment by avierr** [comment] 2019-07-03 15:31
Don't tick "Use VirtualBox instead of Native on next restart" unless you want a slow as hell container.
This is a bad work around, it's a shame it doesn't work with default native ones.

Better alternative is to: `docker  image ls`
and then `docker image rm <iamgeId>`

Please re-open the issue, the issue exists even on the latest version

**Comment by ruizanthony** [comment] 2019-08-29 16:39
as avierr pointed out, the issue is still present in latest version (0.17.7).
Not only the local images are not showing, but also, clicking on the button "my images" makes kitematic bug completely :
clicking on "filter by All" will not show anything
clicking on containers in the left side bar do not show the usual stop/start buttons
clicking on the gear icon to access kitematic preferences do not have any effect

**Comment by AlBundy33** [comment] 2019-08-30 14:18
@avierr this is still an issue. :-(

**Comment by imtiazwazir** [comment] 2019-10-29 21:54
+1

**Comment by Robar666** [comment] 2019-11-06 09:56
+1

**Comment by DerekToop** [comment] 2019-11-08 00:42
+1
![kitematic-cannot-load-local-images](https://user-images.githubusercontent.com/29216624/68439705-8c079800-0218-11ea-934d-b12847ef62bb.gif)

**Comment by Nosferican** [comment] 2019-11-19 05:21
I can confirm the same behavior posted above with OSX `10.15.1` and Docker Desktop `2.1.0.4`.

**Comment by AlBundy33** [comment] 2019-12-09 20:00
maybe you should add your comments to #5234 because I think nobody reads them due to the closed status.

**Comment by cilto** [comment] 2020-01-05 06:32
This is actually related to the docker tag variable type issue.
Considering recent low activity in the main repo, I uploaded fixed release here: https://github.com/cilto/kitematic/releases/tag/v0.17.9-hf.1.
Using this version, you can see your local images without hang-up. Please feel free to use it.

**Comment by avierr** [comment] 2020-01-07 17:52
Thanks @cilto !! You the saviour
