### ISSUE TITLE
Hivemall Docker Image 

### ISSUE THREAD

**Issue by DevalNaik** [docker/kitematic#3955] opened 2018-07-09 10:38 UTC
### Expected behavior
It should able to download and run.

### Actual behavior
Not able to download. 
### Information about the Issue
**Error** :- 
(HTTP code 404) unexpected - manifest for hivemall/latest:latest not found.

### Steps to reproduce the behavior

  1. Search Hivemall
  2. Try to download by clicking _Create_

**Comment by thaJeztah** [comment] 2018-07-09 10:42
the `hivemail/latest` repository does not have a `:latest` tag, only a `:20170517` tag; https://hub.docker.com/r/hivemall/latest/tags/

Looks like the `hivemail/latest` repository does not have a `:latest` tag, , only a `:20170517` tag; so you will have to specify a specific tag to use https://hub.docker.com/r/hivemall/latest/tags/

<img width="263" alt="screen shot 2016-12-10 at 18 06 43" src="https://cloud.githubusercontent.com/assets/1804568/21074843/78797c96-bf03-11e6-9dcc-e0256f52d642.png">

<img width="273" alt="screen shot 2016-12-10 at 18 06 28" src="https://cloud.githubusercontent.com/assets/1804568/21074844/7ef93138-bf03-11e6-8965-783514a78f89.png">

**Comment by thaJeztah** [comment] 2018-07-09 10:42
Closing because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-07-09 10:42 UTC
