### ISSUE TITLE
error while pulling node image

### ISSUE THREAD

**Issue by intikhabalam** [docker/kitematic#5720] opened 2020-07-18 13:02 UTC
### Expected behavior
system should download the node image

### Actual behavior
getting following error:
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

### Steps to reproduce the behavior

  1. docker pull node
  2. getting error ::no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

**Comment by thaJeztah** [comment] 2020-08-03 10:28
The node images are only available as Linux images. If you are using Docker Desktop, you need to switch Docker to run Linux containers instead of native Windows containers; https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers


This is not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2020-08-03 10:28 UTC
