### ISSUE TITLE
Installation of docker container in Kitematic failed.

### ISSUE THREAD

**Issue by hicke** [docker/kitematic#4350] opened 2018-12-04 08:01 UTC
### Expected behavior

Install the container

### Actual behavior

Got an error:

(HTTP code 404) unexpected - {"message":"manifest for elasticsearch:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2018-12-13 12:37
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:37 UTC
