### ISSUE TITLE
refresh in "my images"

### ISSUE THREAD

**Issue by githomboz** [docker/kitematic#3211] opened 2017-10-25 13:55 UTC
### Expected behavior

automatic refresh capability within kitematic app component "my images"

### Actual behavior

Must close kitematic and reopen in order for newly built images to appear for launch

### Steps to reproduce the behavior

  1. open kitematic
  2. click on "my images"
  3. view images that are visible
  4. perform docker build command from command prompt
  5. return to kitematic the new image is not vivible
  6. close kitematic
  7. open kitematic - images now visible

**Comment by mhelmetag** [comment] 2017-10-27 06:17
I think this is a duplicate of #2609

**Comment by FrenchBen** [comment] 2017-10-27 09:41
Duplicate of #2609 - closing

**Closed by FrenchBen** 2017-10-27 09:41 UTC
