### ISSUE TITLE
Unable to load local image

### ISSUE THREAD

**Issue by psftc** [docker/kitematic#3694] opened 2018-03-27 00:10 UTC
### Expected behavior
Load the local image in Docker and create a new container
### Actual behavior
404 no such image
### Information about the Issue
Mac OS X, 10.13.3 (17D102)
Docker version (about Docker) Fatal Error Segmentation violation exception.

### Steps to reproduce the behavior

  1. Docker command line
  2. docker pull docker.elastic.co/kibana/kibana:6.2.3
  3. Reinstall Virtual Box to get Kitematic working again on my machine
  4. Observe that there is an image called kibana.
  5. Attempt to create a container from the image.

**Comment by FrenchBen** [comment] 2018-03-27 21:37
Duplicate of #3620 - Closing

**Closed by FrenchBen** 2018-03-27 21:37 UTC

**Comment by KevinHubs** [comment] 2019-12-05 02:39
Hello, docker segmentation violation exception. How to solve this exception?

**Comment by KevinHubs** [comment] 2019-12-05 02:40
@psftc Hello, docker segmentation violation exception. How to solve this exception?
