### ISSUE TITLE
network error window

### ISSUE THREAD

**Issue by feichangshun** [docker/kitematic#1927] opened 2016-08-23 03:57 UTC
### Steps to reproduce the behavior

  1. ...Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mysql/images. You may want to check your internet connection or if you are behind a proxy.
  2. ...

**Comment by Fahrradflucht** [comment] 2016-08-23 06:21
Duplicate of #1904

**Comment by FrenchBen** [comment] 2016-08-26 01:25
thanks @Fahrradflucht for the help!
@feichangshun since you're in Beijing I'm guessing you are behind a proxy and thus need to do the following:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Closed by FrenchBen** 2016-08-26 01:25 UTC
