### ISSUE TITLE
Consider value of `$MACHINE_STORAGE_PATH` 

### ISSUE THREAD

**Issue by normenmueller** [docker/kitematic#1640] opened 2016-04-21 15:19 UTC
### Expected behavior

If `$MACHINE_STORAGE_PATH` is set, then use this one instead of default `~/.docker`.
### Actual behavior

Ignores `$MACHINE_STORAGE_PATH` but creates machines etc. at `~/.docker`.
### Information about the Issue

Cf. [Fix broken --storage-path flag](https://github.com/docker/machine/pull/1941/files)
### Steps to reproduce the behavior
1. Set `$MACHINE_STORAGE_PATH` to a path unequal to `~/.docker`
2. Start Kitematic

**Comment by FrenchBen** [comment] 2016-04-22 23:08
We actually call out to docker machine directly. I'm guessing the issue is that you set the variable in your ENV, that is unknown to Kitematic. 

Try this.
1. Set your env var for `$MACHINE_STORAGE_PATH`
2. Then run: `open /Applications/Kitematic\ \(Beta\).app`

See if it respects the path.

**Comment by normenmueller** [comment] 2016-04-23 06:21
Well, we are getting closer :)

```
$ echo $MACHINE_STORAGE_PATH
/Users/nrm/VM/VirtualBox/Docker
$ open /Applications/Docker/Kitematic\ \(Beta\).app
```

Created a new `default` VM, but than complains "Certificate directory does not exist". However:

```
[~/VM/VirtualBox]
$ tree -L 2 Docker
Docker
├── cache
│   └── boot2docker.iso
├── certs
│   ├── ca-key.pem
│   ├── ca.pem
│   ├── cert.pem
│   └── key.pem
└── machines
    ├── bd-hadoop-sandbox
    ├── bd-spark-sandbox
    └── default
```

**Comment by FrenchBen** [comment] 2016-04-25 17:28
with the env var set, `docker-machine ls` doesn't return the proper machine?

Ping @nathanleclaire Is this the proper way to set this up?

**Comment by normenmueller** [comment] 2016-04-25 20:06
Still a newbie to docker, which env var must be set in order to get a list of all machines?
The command `eval "$(docker-machine env default)"` is to set env for `default`, right?

**Comment by nathanleclaire** [comment] 2016-04-25 20:45
It should work fine with just `MACHINE_STORAGE_PATH`.

This is with 0.7.0?

**Comment by nathanleclaire** [comment] 2016-04-25 20:46
FYI, can't discern if you're doing this here, but creating machines with the same name (even in different storage paths) is likely to cause issues.

**Comment by normenmueller** [comment] 2016-04-25 21:37
Well, it works with `MACHINE_STORAGE_PATH` in terms of creating a `default` at this path, even there exist already machines. Why is that?

Yes, I'm `0.7.0`.

However, after I created manually a `default` and then started Kitematic I got

```
Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.7.0, build a650a40,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:57304,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:57308,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.0.18r106667,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Name: vboxnet0,(default) DBG | GUID: 786f6276-656e-4074-8000-0a0027000000,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.99.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: ,(default) DBG | IPV6NetworkMaskPrefixLength: 0,(default) DBG | HardwareAddress: 0a:00:27:00:00:00,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Up,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet0,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) Calling .GetConfigRaw,(default) Calling .Create,(default) DBG | local Boot2Docker ISO version: v1.11.0,(default) DBG | Creating disk image...,(default) DBG | Creating 20000 MB hard disk image...,(default) DBG | Writing magic tar header,(default) DBG | Writing SSH key tar header,(default) DBG | Calling inner createDiskImage,(default) DBG | &{/usr/local/bin/VBoxManage [/usr/local/bin/VBoxManage convertfromraw stdin /Users/nrm/.docker/machine/machines/default/disk.vmdk 20971520000 --format VMDK] [] <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>},(default) DBG | Starting command,(default) DBG | Copying to stdin,(default) DBG | Filling zeroes,(default) DBG | Converting from raw image file="stdin" to file="/Users/nrm/.docker/machine/machines/default/disk.vmdk"...,(default) DBG | Creating dynamic image with size 20971520000 bytes (20000MB)...,(default) DBG | Closing STDIN,(default) DBG | Waiting on cmd,(default) DBG | COMMAND: /usr/local/bin/VBoxManage createvm --basefolder /Users/nrm/.docker/machine/machines/default --name default --register,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Virtual machine 'default' is created and registered.,(default) DBG | UUID: 86a91c43-0c55-4514-a15d-869d4f664686,(default) DBG | Settings file: '/Users/nrm/.docker/machine/machines/default/default/default.vbox',(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | VM CPUS: 1,(default) DBG | VM Memory: 2048,(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 on --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --nic1 nat --nictype1 82540EM --cableconnected1 on,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage storagectl default --name SATA --add sata --hostiocache on,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | VBoxManage: error: Storage controller named 'SATA' already exists,(default) DBG | VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports,(default) DBG | VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1062 of file VBoxManageStorageController.cpp,(default) DBG | },Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage storagectl default --name SATA --add sata --hostiocache on failed:,VBoxManage: error: Storage controller named 'SATA' already exists,VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports,VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1062 of file VBoxManageStorageController.cpp,,open /Users/nrm/.docker/machine/machines/default/default/Logs/VBox.log: no such file or directory,notifying bugsnag: [Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage storagectl default --name SATA --add sata --hostiocache on failed:,VBoxManage: error: Storage controller named 'SATA' already exists,VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports,VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1062 of file VBoxManageStorageController.cpp,],
```

**Comment by nathanleclaire** [comment] 2016-04-25 21:51
Looks like it's complaining because some virtual hardware that you are trying to create already exists with that name, no?  Does it work if you create a machine with name other than `default`?

**Comment by nathanleclaire** [comment] 2016-04-25 21:51
Why do you desire to use location other than `~/.docker`?

**Comment by normenmueller** [comment] 2016-04-25 22:01
`docker-machine` does not list anything. But opening up VirtualBox shows a lot of broken docker machines. After I removed all of them, it worked again. 

Why to choose another location? Well, I have a dedicated dir `/Users/nrm/VM` and want all my VMs go in  there and then exclude this dir form TimeMachine.

**Comment by Verayth** [comment] 2016-05-02 23:16
I'm having the same problem with the Windows version (see #1653), and I need this fixed because my boot C: drive doesn't have enough space to hold large docker images. `docker-machine ls` shows the 'default' machine running, but Kitematic just can't see it after it was the one that created the machine.

As a work-around, I tried creating a windows junction to try and force Kitematic to the new location, but that doesn't work either and now I get a `Certificate directory does not exist` error after the docker machine is created completely successfully.

**Comment by Maks3w** [comment] 2016-07-07 10:38
For the issue about `Certificate directory does not exists` Kitematic should honor the value of `DOCKER_CERT_PATH`

**Comment by Maks3w** [comment] 2016-07-16 12:28
A workaround is create a link between ~/.docker/machine and MACHINE_STORAGE_PATH

For windows this is

`mklink /J %USERPROFILE%/.docker/machine %MACHINE_STORAGE_PATH%`

For *Nix this is

`ln -s ~/.docker/machine $MACHINE_STORAGE_PATH`

**Comment by thomasdarimont** [comment] 2016-07-17 00:27
in my local build with the PR #1831 applied I can successfully create and connect to docker-machines  created outside of the user home directory without having to create any links.

**Comment by FrenchBen** [comment] 2016-07-21 00:35
thanks @thomasdarimont for the PR - I'll review it and will provide feedback as needed.

**Comment by karneaud** [comment] 2016-08-19 03:13
+1 dump. Kinematic Beta still doesn't honour the **MACHINE_STORAGE_PATH** env

**Comment by Maks3w** [comment] 2016-08-19 17:02
@karneaud v0.12.0 it's supposed to support the env var

https://github.com/docker/kitematic/releases/tag/v0.12.0

**Comment by garu57** [comment] 2017-02-24 09:30
Hi all,
i think there are still some problems.
I installed the just downloaded Docker Toolbox on Win 7 Pro SP1.
If i let the default setup, `%USERPROFILE%\.docker`, the vm is created once and reused at each Kitematic start.
If i use the setup detailed above, the vm is indeed created in the location pointed by `MACHINE_STORAGE_PATH` and Kitematic starts correctly.

The problem is that EACH TIME i start Kitematic the VM is scratched and recreated so loosing any previous work.

Tried also with last released version, 0.13.1, but i got the same behavior.

Regards,
Gabriele

PS:
Sorry for the double post, i commented wrongly on the closed #1831 PR instead of here.

**Comment by streiml** [comment] 2017-03-17 12:15
I have the same problem as @garu57 mentioned before. It is also necessary to set DOCKER_CERT_PATH explict and correctly, otherwise the error `Certificate directory does not exist` appears.

**Comment by cosmomill** [comment] 2017-04-28 08:02
Hello,

after a closer look at the code it turns out that `nonNativeSetup` in [SetupUtil.js](https://github.com/docker/kitematic/blob/d6a2ae3906b0295eabb19cdcfb2f02f68085456d/src/utils/SetupUtil.js#L137) does not respect `MACHINE_STORAGE_PATH`.
This works for me:
```
if (process.env.MACHINE_STORAGE_PATH) {
     let exists = await virtualBox.vmExists(machine.name()) && fs.existsSync(path.join(process.env.MACHINE_STORAGE_PATH, 'machines', machine.name()));
   } else {
     let exists = await virtualBox.vmExists(machine.name()) && fs.existsSync(path.join(util.home(), '.docker', 'machine', 'machines', machine.name()));
}
```

**Comment by FrenchBen** [comment] 2017-04-28 18:38
@cosmomill Would you mind sending in a PR with your above fix?

**Comment by FrenchBen** [comment] 2017-05-02 18:29
Fixed by https://github.com/docker/kitematic/pull/2602 - Thanks @cosmomill

**Closed by FrenchBen** 2017-05-02 18:29 UTC

**Comment by nsidhaye** [comment] 2017-08-07 04:30
Saw strange behavior. Opened issue #2933
