### ISSUE TITLE
pull Elasticsearch:latest image fail

### ISSUE THREAD

**Issue by godlockin** [docker/kitematic#4275] opened 2018-11-12 06:21 UTC
### Expected behavior
Downloading Image of Elasticsearch

### Actual behavior
<img width="523" alt="image" src="https://user-images.githubusercontent.com/31117750/48329973-ea417f80-e685-11e8-9658-4ad8fc38f756.png">

### Information about the Issue
Env: Mac Mojave 10.14.1

### Steps to reproduce the behavior

  1. Open the Kitematic app
  2. Click "NEW" and select the Elasticsearch 
  3. The 404 stuff happens while when I did the same on a, maybe MongoDb image, the downloading Image page shows up

**Comment by bmomartins** [comment] 2018-11-15 00:03
Same issue here.

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC
