### ISSUE TITLE
Error: Problem about download

### ISSUE THREAD

**Issue by zkh90644** [docker/kitematic#1808] opened 2016-07-06 00:09 UTC
I want to download a container in the app.
Than when I cancel the container and download it again, the app shows that there are 2 progress bar in the same container,just like there are 2 thread to download the container.

**Comment by FrenchBen** [comment] 2016-07-07 22:45
Screenshot and steps to reproduce?
If you click on download and then download again, 2 containers will be created.

**Comment by FrenchBen** [comment] 2016-08-26 19:04
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Closed by FrenchBen** 2016-08-26 19:04 UTC
