### ISSUE TITLE
Clicking Docker CLI opens Terminal instead of iTerm

### ISSUE THREAD

**Issue by petems** [docker/kitematic#1502] opened 2016-02-29 16:23 UTC
* Expected behaviour: Clicking Docker CLI opens iTerm and runs Docker loading script
* Actual behaviour: Clicking Docker CLI opens Terminal and runs Docker loading script

Example: (Note iTerm is installed and running, I show it open at the end)
![dockercli](https://cloud.githubusercontent.com/assets/1064715/13400680/be1269f4-df00-11e5-9503-91fdd4cefc4f.gif)

 Version Information:
<img width="498" alt="screenshot 2016-02-29 16 20 05" src="https://cloud.githubusercontent.com/assets/1064715/13400573/52a30296-df00-11e5-956e-0d1e91f321bc.png">

**Comment by FrenchBen** [comment] 2016-03-01 00:59
What version of iTerm are you using?
I have iTerm `2.1.4` installed, when I click on Docker CLI a new tab opens in my existing iTerm window - If no iTerm window is open, a new one is opened.

**Comment by petems** [comment] 2016-03-01 08:43
<img width="332" alt="screenshot 2016-03-01 08 43 00" src="https://cloud.githubusercontent.com/assets/1064715/13421962/a295423a-df89-11e5-855c-c032425869f5.png">

v2.9.2016206

**Comment by gleblanc1783** [comment] 2016-03-01 17:14
Confirmed. With iTerm2 v2.1.4 the Kitematic CLI works as intended.

**Comment by petems** [comment] 2016-03-01 17:59
Hmmm, how would one fix this? I don't know enough node to know why this happens...

I'm guessing it's the https://github.com/docker/kitematic/blob/master/resources/terminal file, but when I run the osascript it seems to determine that it's iterm ok:
![itermornot](https://cloud.githubusercontent.com/assets/1064715/13436481/5b1cf30a-dfd7-11e5-885b-82fd95d2c9fa.gif)

**Comment by FrenchBen** [comment] 2016-03-01 23:59
@petems there's a PR against it, but since it's mainly due to beta/nightly, it hasn't been merged:
https://github.com/docker/kitematic/pull/855

We don't want to keep making changes to a beta/nightly build as it may add more code changes than wanted. Once this goes to stable, we'll be able to merge if it's still an issue.

Thanks @gleblanc1783 for confirming that with stable releases it works as expected.

**Closed by FrenchBen** 2016-03-01 23:59 UTC

**Comment by jshields** [comment] 2020-06-04 20:53
I am experiencing this issue on iTerm2 version "Build 3.3.9" and Docker Desktop for Mac version 2.3.0.3

**Comment by robahl** [comment] 2021-01-08 12:48
Clicking CLI from Docker opens Terminal.app and not iTerm (as I want).
