### ISSUE TITLE
(HTTP code 404) unexpected

### ISSUE THREAD

**Issue by negal** [docker/kitematic#4240] opened 2018-11-01 03:05 UTC
### Steps to reproduce the behavior

  1. I create a elasticsearch container official

  2."(HTTP code 404) unexpected - {"message":"manifest for elasticsearch:latest not found"}"

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC
