### ISSUE TITLE
error in setup

### ISSUE THREAD

**Issue by vipulg** [docker/kitematic#1889] opened 2016-08-06 04:01 UTC
failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-252995730 /var/lib/docker/image/aufs/layerdb/sha256/e706e7046115cee731550afd12e36b4016360a011dcef13508a8118184d23baa: directory not empty

**Comment by FrenchBen** [comment] 2016-08-08 17:45
Could you provide steps to reproduce? are you using Docker for Mac?

**Comment by FrenchBen** [comment] 2016-08-26 19:06
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Closed by FrenchBen** 2016-08-26 19:06 UTC

**Comment by adam-eclabs** [comment] 2016-09-29 14:23
I have the same issue when trying to add Prestashop container.
Octobercms containers seems to work

failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-038466970 /var/lib/docker/image/aufs/layerdb/sha256/383a7378a836c1cefa5ee256ec02abab4ad8502e129a8f8e89d31725dfa78254: directory not empty

After checking the VM the above directory was not there.
I am using Docker for mac and running EL Capitan 10.11.6
