### ISSUE TITLE
(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### ISSUE THREAD

**Issue by VVilku** [docker/kitematic#4299] opened 2018-11-16 12:52 UTC
### Expected behavior
Non 404
### Actual behavior
(HTTP code 404) unexpected - manifest for elasticsearch:latest not found
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2018-12-13 12:36
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:36 UTC

**Comment by kalpeshgamit** [comment] 2019-03-07 01:52
same here ...
