### ISSUE TITLE
cannot download cassandra

### ISSUE THREAD

**Issue by elinalin** [docker/kitematic#3245] opened 2017-10-31 17:23 UTC
cannot download cassandra 
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/cassandra/manifests/latest: unauthorized: incorrect username or password"}

**Comment by mhelmetag** [comment] 2017-10-31 20:18
@elinalin , I think this is a duplicate of #3244 . Can you close this and add the extra info to the first issue (#3244)?

**Comment by FrenchBen** [comment] 2017-10-31 21:36
Duplicate of #3244

**Closed by FrenchBen** 2017-10-31 21:36 UTC
