### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by coption** [docker/kitematic#4028] opened 2018-08-07 01:50 UTC
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:49648->192.168.65.1:53: i/o timeout"}

**Comment by jeanlaurent** [comment] 2018-08-24 13:01
closing as duplicate of #4029

**Closed by jeanlaurent** 2018-08-24 13:01 UTC
