### ISSUE TITLE
login won't accept my email address

### ISSUE THREAD

**Issue by ormico** [docker/kitematic#2688] opened 2017-05-25 14:23 UTC
### Expected behavior
on login screen prompt is for email or username. if I enter my email address, I expect to be able to use that for the login id instead of my usernmame.

### Actual behavior
error is displayed in red when you tab or click our of email/username field stating "Must be 4-30 lowercase letters or numbers, or a valid email".
email is valid and is between 4 an 30 characters long: z@ormi.co

after entering password, login button will not register click

changed login id to username and click Login button and was logged in.

### Information about the Issue
my email ends in .co not .com This is a valid email and should have been accepted.

### Steps to reproduce the behavior
see above

**Comment by FrenchBen** [comment] 2017-05-26 23:57
Fixed with https://github.com/docker/kitematic/pull/2574

**Closed by FrenchBen** 2017-05-26 23:57 UTC

**Comment by chemiu** [comment] 2019-03-21 07:49
looks like the issue is back
