### ISSUE TITLE
Characters on pop-ups appear as squares

### ISSUE THREAD

**Issue by claudiunv** [docker/kitematic#2829] opened 2017-07-12 13:06 UTC
### Expected behavior
When a pop-up is appearing should display the required text.

### Actual behavior
All the application's popups are displayng squares instead of text.

### Information about the Issue
The application is installed on Arch Linux (Manjaro) from AUR.

### Steps to reproduce the behavior

  1. Start application
  2. Delete a container
  3. The pop-up window will have the text replaced with squares
![popup-square](https://user-images.githubusercontent.com/1399786/28118968-1e26efa2-670b-11e7-9001-7aacc6ebc2fe.png)

**Comment by claudiunv** [comment] 2017-07-12 13:12
- What operating system and version?
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0.2
Codename:	Gellivara

 - What version of kitematic?
kitematic  0.17.0-1

 - What version of docker?
docker  1:17.05.0-1

**Comment by FrenchBen** [comment] 2017-07-12 17:30
Are you using a special font/character encoding?

**Comment by claudiunv** [comment] 2017-07-13 10:08
These are my locales. The ro_RO.UTF-8 have nothing special than some diacritics and the rest of characters are Latin, nothing special.

### $ locale

LANG=en_GB.utf8
LC_CTYPE=en_GB.utf8
LC_NUMERIC=ro_RO.UTF-8
LC_TIME=ro_RO.UTF-8
LC_COLLATE="en_GB.utf8"
LC_MONETARY=ro_RO.UTF-8
LC_MESSAGES="en_GB.utf8"
LC_PAPER=ro_RO.UTF-8
LC_NAME=ro_RO.UTF-8
LC_ADDRESS=ro_RO.UTF-8
LC_TELEPHONE=ro_RO.UTF-8
LC_MEASUREMENT=ro_RO.UTF-8
LC_IDENTIFICATION=ro_RO.UTF-8
LC_ALL=

**Comment by mijailr** [comment] 2017-07-27 07:40
I have the same issue.

**Comment by FrenchBen** [comment] 2017-07-27 22:24
@mijailr Can you also share your locales so that we can compare?

**Comment by mijailr** [comment] 2017-07-28 15:58
@FrenchBen 

    LANG=es_VE.UTF-8
    LC_CTYPE=es_VE.UTF-8
    LC_NUMERIC="es_VE.UTF-8"
    LC_TIME="es_VE.UTF-8"
    LC_COLLATE="es_VE.UTF-8"
    LC_MONETARY="es_VE.UTF-8"
    LC_MESSAGES="es_VE.UTF-8"
    LC_PAPER="es_VE.UTF-8"
    LC_NAME="es_VE.UTF-8"
    LC_ADDRESS="es_VE.UTF-8"
    LC_TELEPHONE="es_VE.UTF-8"
    LC_MEASUREMENT="es_VE.UTF-8"
    LC_IDENTIFICATION="es_VE.UTF-8"
    LC_ALL=

But i see this problem with other software in electron. 
 - electron/electron#9616
 - camunda/camunda-modeler#594

I think the problem is with the embeded version of chrome, so if we update the version of electron it will be fixed. I will try and report if i have any success.

**Comment by alex4o** [comment] 2017-11-15 17:33
https://github.com/electron/electron/issues/9616
It was fixed in the latest electron.

**Comment by FrenchBen** [comment] 2017-11-15 18:38
@alex4o Can you help integrate it?

**Comment by alex4o** [comment] 2017-11-16 00:18
I have opened a pull request, hope that helps.
https://github.com/docker/kitematic/pull/3313

**Comment by FrenchBen** [comment] 2017-11-17 22:16
Fixed by https://github.com/docker/kitematic/pull/3313

**Closed by FrenchBen** 2017-11-17 22:16 UTC
Labels: compatibility, exp/expert, help wanted, linux

**Comment by Ethergeist** [comment] 2017-11-22 06:32
This is still happening using Kitematic 0.17.3 on Arch x64 - Really looks like a missing font, or perhaps unsupported locale settings. All dialog boxes still display fonts as boxes/cubes.
