### ISSUE TITLE
looking for php-mysql smarty container

### ISSUE THREAD

**Issue by biomassives** [docker/kitematic#1468] opened 2016-02-13 05:22 UTC
will build one and share it back if I don't see it.

**Comment by biomassives** [comment] 2016-02-13 05:22
came here when 'smartypants' broke

**Comment by FrenchBen** [comment] 2016-02-15 22:43
not really sure what the issue is, as there is no details of errors/issues. Closing until further details are provided

**Closed by FrenchBen** 2016-02-15 22:43 UTC
