### ISSUE TITLE
Cannot install elasticsearch image

### ISSUE THREAD

**Issue by KyongSik-Yoon** [docker/kitematic#4339] opened 2018-11-29 07:38 UTC
### Expected behavior
Selected image should be installed.

### Actual behavior
Error message displayed that (HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### Information about the Issue
My environment is MAC OS 10.14.1

### Steps to reproduce the behavior

  1. Press NEW button
  2. Type elasticsearch on text field to find official image 
  3. Click CREATE button

**Comment by Traste** [comment] 2018-11-29 10:02
Expected behavior
Selected image should be installed.

Actual behavior
(HTTP code 500) server error - manifest unknown: manifest unknown

Information about the Issue
My environment is Windows 10 Professional with Docker for Windows and Kitematic 0.17.5.0 downloaded from the link provided by Docker for Windows and installed as described.

Steps to reproduce the behavior
Press NEW button
Type elasticsearch on text field to find official image
Click CREATE button

**Comment by stephen-turner** [comment] 2018-12-13 12:37
Dupe of #4171.

**Closed by stephen-turner** 2018-12-13 12:37 UTC
