### ISSUE TITLE
Login hangs

### ISSUE THREAD

**Issue by SoyYop** [docker/kitematic#4101] opened 2018-09-14 01:11 UTC
### Expected behavior
Being able to log in to docker hub

### Actual behavior
Small wheel appears next to log-in box and stays running, ui unresponsive

### Information about the Issue
Fresh install on windows with Visual Studio 2017, being able to run container, running asp.net container listed and shows homepage on "web preview" when clicked
Docker running and logged in

### Steps to reproduce the behavior

  1. Click on "Log in"
  2. Put username & password
  3. Click login blue button
  4. Small wheel appears and runs forever, it never logs in nor releases ui, I can just close it

**Comment by peterlobster** [comment] 2018-09-14 10:19
Duplicate of #4094 #4099 #4098

**Comment by ulrich** [comment] 2019-10-02 07:44
Issue fixed, Kitematic can login to hub now.

Thank you for your feedback.

**Closed by ulrich** 2019-10-02 07:44 UTC
