### ISSUE TITLE
Kitematic shows that it is updating the VM at the top 

### ISSUE THREAD

**Issue by NileshArnaiya** [docker/kitematic#1790] opened 2016-06-29 18:25 UTC
We're sorry there seems to be an error 

  1. ...Timeout error - Try and restart your VM by running:

"docker-machine restart default" in a terminal

**Comment by FrenchBen** [comment] 2016-06-29 19:02
Please provide steps to reproduce and screenshots to help understand what's going on

**Comment by FrenchBen** [comment] 2016-08-26 19:03
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Closed by FrenchBen** 2016-08-26 19:03 UTC
