### ISSUE TITLE
Trying to download bdu spark2

### ISSUE THREAD

**Issue by jgperrin** [docker/kitematic#2758] opened 2017-06-18 19:47 UTC
### Expected behavior
download & run?

### Actual behavior
message saying: error unauthorized: authentication required

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment] 2017-06-20 18:13
Unable to reproduce this - Please provide exact steps to reproduce and docker versions

**Comment by FrenchBen** [comment] 2017-10-23 15:18
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Closed by FrenchBen** 2017-10-23 15:18 UTC
Labels: more-info-needed

**Comment by jgperrin** [comment] 2017-10-23 15:21
Was not able to reproduce issue lately. Merci
