### ISSUE TITLE
image name in UI of remote pulled image not complete

### ISSUE THREAD

**Issue by mqsquidy** [docker/kitematic#1908] opened 2016-08-17 17:38 UTC
### Expected behavior
see the full name of image when displaying MyImages after image is pulled from remote repo
### Actual behavior
i only see first part of path, ie 2 Images:
docker.us-east-1.aws.aol.com/metro/tsdb-splicer:0.0.6
docker.us-east-1.aws.aol.com/metro/opentsdb-reader:0.0.4
both display as "docker.us-east-1.aws.aol.com, (newline) metro, with version tag correct"
the version tag is the only way I can tell which is which
### Steps to reproduce the behavior

  1. docker login using cmd line terminal
  2. docker pull image

**Comment by FrenchBen** [comment] 2016-08-23 02:43
Duplicate of #1840

**Closed by FrenchBen** 2016-08-23 02:43 UTC
