### ISSUE TITLE
Removed containers aren't removed

### ISSUE THREAD

**Issue by maklipsa** [docker/kitematic#1688] opened 2016-05-20 10:39 UTC
### Expected behavior
It will be removed

### Actual behavior
The container is still listed.
### Steps to reproduce the behavior

  1.Created a container
  2. Opened Kitematic
  3. Clicked remove on the container
  4. When clicking on the removed container this error message is displayed:

Timeout error - Try and restart your VM by running:

"docker-machine restart default" in a terminal

**Comment by FrenchBen** [comment] 2016-05-20 21:00
Every container I remove gets removed. Can you share your version of kitematic and Docker?

**Comment by maklipsa** [comment] 2016-05-21 10:51
After some investigation what i discovered that avter hibernation the hyper v machine had to be restarted, because it was down. Kitematic was showing the not removed containers as ok, and the removed as failed only because only they were refreshed. After trying to restart the not removed container it also reported that issue.

**Comment by FrenchBen** [comment] 2016-05-23 19:06
You're mentioning `hyperV` yet I see no information as to a hyperV use-case within the steps and details you provided. 
`docker-machine restart default` points to using Virtualbox; Not being provided with your exact setup/steps to reproduce makes it extremely difficult for me to find the issue you mention.

**Comment by FrenchBen** [comment] 2016-08-26 01:46
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Closed by FrenchBen** 2016-08-26 01:46 UTC
