### ISSUE TITLE
Docker Image Not Found

### ISSUE THREAD

**Issue by volkanalay** [docker/kitematic#5310] opened 2019-09-23 07:53 UTC
### Expected behavior
Success image installation
### Actual behavior
Error on installing image
### Information about the Issue
Image could not be found on the repo. And following error occurred on installing image "(HTTP code 404) unexpected - manifest for elasticsearch:latest not found: manifest unknown: manifest unknown"

**Comment by schrockwell** [comment] 2019-09-23 21:12
According to [this page](https://hub.docker.com/_/elasticsearch):

> Note: Pulling an images requires using a specific version number tag. The latest tag is not supported.

**Comment by volkanalay** [comment] 2019-09-23 21:28
Hi schrockwell,
Thanks for the reply but something wrong with the ui for docker kitematic. When I searched and select the image from kitematic it's automatically tries to pull latest tagged version. I don't know how could I change it.

**Comment by schrockwell** [comment] 2019-09-24 12:22
Sorry if I wasn't clear – I'm having the same problem. I was posting that as a potential cause for someone else who might be able to fix it.

**Comment by fanntom** [comment] 2019-09-26 10:43
@volkanalay @schrockwell That is possibly the cause of the problem. You can solve this problem by changing the tag used to download the image.
In when selecting the image you want to download in Kitematic, click on the '...' button next to create, click on selected tag: latest and search for the tag you want to use.

**Comment by jai555** [comment] 2019-10-14 02:17
I am also facing the same issue while pulling the image (MySQL) using the kitematic UI.

**Comment by ErtugrulSener** [comment] 2019-10-23 19:35
Duplicate of #5323

**Comment by thaJeztah** [comment] 2019-12-27 12:10
That repository does not have a `:latest` tag, so you will have to specify a specific tag to use; here's the steps to do so:

<img width="288" alt="screenshot 2019-02-28 at 11 13 10" src="https://user-images.githubusercontent.com/1804568/53559259-0dffd700-3b4a-11e9-84dc-aca7eadb8266.png">

Click on the `...` button to view the image's details

<img width="289" alt="screenshot 2019-02-28 at 11 13 25" src="https://user-images.githubusercontent.com/1804568/53559322-27088800-3b4a-11e9-91ec-88ca26854d28.png">

Click on the `Selected tag: latest` to open the "tag selection" window

<img width="293" alt="screenshot 2019-02-28 at 11 13 48" src="https://user-images.githubusercontent.com/1804568/53559363-3be51b80-3b4a-11e9-8bd0-c5da16e891cd.png">

Click the tag / version of the image you want to run

<img width="296" alt="screenshot 2019-02-28 at 11 13 57" src="https://user-images.githubusercontent.com/1804568/53559412-51f2dc00-3b4a-11e9-924a-2929fafdcdbb.png">

Click the `(X)` to close the tag selector window

<img width="295" alt="screenshot 2019-02-28 at 11 14 16" src="https://user-images.githubusercontent.com/1804568/53559443-62a35200-3b4a-11e9-8691-57e375a90a7b.png">

Click on the `Create` button to pull the image and start the container

**Closed by thaJeztah** 2019-12-27 12:10 UTC
