### ISSUE TITLE
features stop containers, manage ports and deployments ?

### ISSUE THREAD

**Issue by sallespro** [docker/kitematic#207] opened 2015-03-02 14:01 UTC
hei huys, great job, lots of bugs and minor improvements.

the Important stuff from my perspective are 

1.  to save resources and run a couple of containers while some others are just stopped.

2. choose the ports mapped in mac.

3. to publish your docker in a self hosted docker server, or third parties who offer docker image hosting.

**Comment by trezm** [comment] 2015-03-12 14:51
:+1:

**Comment by mainiak** [comment] 2015-03-12 16:40
:+1:

**Comment by yakovkhalinsky** [comment] 2015-03-12 18:59
Duplicate of #164

**Comment by tslater** [comment] 2015-03-14 07:39
+1

**Comment by yborunov** [comment] 2015-03-18 00:24
Voting for stopping container opportunity

**Comment by FrenchBen** [comment] 2016-08-26 19:09
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.

**Closed by FrenchBen** 2016-08-26 19:09 UTC
Labels: feature
