### ISSUE TITLE
Dialog does not display text

### ISSUE THREAD

**Issue by darkstone** [docker/kitematic#3723] opened 2018-04-05 10:28 UTC
### Expected behavior

Expected to see dialog. 

### Actual behavior

Text is replaced by "blocks"

![Imgur](https://i.imgur.com/W28grjb.png)

### Information about the Issue

Installed via pacman

**Comment by FrenchBen** [comment] 2018-04-06 00:15
Dupe of https://github.com/docker/kitematic/issues/2829

**Closed by FrenchBen** 2018-04-06 00:15 UTC
