### ISSUE TITLE
HTTP code is 500 which indicates error: server error - [object Object]

### ISSUE THREAD

**Issue by pslootweg** [docker/kitematic#1872] opened 2016-08-01 09:19 UTC
### Expected behaviour

Show status of docker image
Allow start/re-start of postgres 9.3.13 image.

### Actual behaviour

The postgres server is shown as 'Stopped' but I know it is running because I can access the DB.
(Actually, it couldn't run because I had another instance running!)
When I try to click Start or Restart an error briefly flashes up:

"HTTP code is 500 which indicates error: server error - [object Object]"

before it is obscured by the log output (which doesn't change.)

### Information about the Issue

This is the first time I've used Kitematic, so this may be a noob problem.
Platform is Mac/OSX

### Steps to reproduce the behavior

  0. Run up a postgres instance - turns out Jira was using THIS instead!
  1. Run Docker with a postgres:9.3.13 image (the DB is intended to be used by Jira)
  2. Run Jira - this is configured with the postgres DB
  3. Install and run Kitematic
  4. Shows Docker postgres DB as Stopped
  5. Click on 'Start' - error flashes briefly

To see the error, go to Settings - scroll down and click on Save - then go to Home tab where the error can be seen.

Unfortunately, the actual cause (i.e. port already in use) is pretty much overlooked.

**Comment by FrenchBen** [comment] 2016-08-01 19:58
Please update to the latest Kitematic to get the proper error instead of the `[object Object]` you're showing above.

**Comment by pslootweg** [comment] 2016-08-01 20:03
I only installed it today! How much more up-to-date do I need to be?!

**Comment by FrenchBen** [comment] 2016-08-01 20:20
@pslootweg How did you install it? I'm only asking because the error report should be more detailed. 
The error you're showing was fixed on `0.11.x`

Can you list the exact images (and tags) used so that I can reproduce on my end?

**Comment by pslootweg** [comment] 2016-08-01 20:40
Think it was a link offered from Docker...
I can check the version tomorrow.

**Comment by FrenchBen** [comment] 2016-08-01 20:42
Please let me know what the version is, so that I can ping the right people to get the links updated.

**Comment by pslootweg** [comment] 2016-08-04 10:22
I have since upgraded and now
I am running Docker Version 1.12.0-beta21 which launches Kinematic 0.12.0

Same problem and same error message.

**Comment by FrenchBen** [comment] 2016-08-04 22:25
I am unable to replicate this issue, as you haven't provided the exact tags used for each image and the settings used for them as well. 
Please provide them, so that I can see the error for myself.

**Comment by pslootweg** [comment] 2016-08-04 22:49
Once again, I don't know what you're talking about.

In Docker, I have a Postgres 9.3.13 image - with port 5432 mapped to local port 5432.
Initially, my problem was that I had a (homebrew) installed Postgres instance. So, when trying to start the Docker image, there would be a port conflict with the system installed Postgres instance.

I then killed the system, installed installed, and found the same result came from trying to start  second Postgres 9.3.13 instance in Docker.

This problem is VERY repeatable - either within Docker, or in fact for any port conflict.

The issue is SIMPLY that a Docker instance can't be started if the port is already in use. Unfortunately, the error reported is completely unrelated.

If a noob like me can replicate this issue so readily, then you're obviously approaching this from an assumption that I am dumb and I have it wrong.

**Comment by FrenchBen** [comment] 2016-08-05 00:32
From kitematic, port mapping is done with a random port and why it wasn't showing any errors from me. 
Providing very little information about the issue you're having makes it difficult for maintainers to determine the root cause of it. 

You mentioned `JIRA` in your first thread (with no info on the version/tag used), yet it seems to have nothing to do with your issue. 

Hence my point that replicating this through kitematic is impossible.
1. Create Postgres container, random port is assigned:
<img width="258" alt="random-port" src="https://cloud.githubusercontent.com/assets/3965324/17422686/0bd62ade-5a69-11e6-897b-02127e1c5dd2.png">
2. Assign the Postgres port:
<img width="254" alt="set-port" src="https://cloud.githubusercontent.com/assets/3965324/17422688/13bf41fe-5a69-11e6-9ef5-564e878408a7.png">
3. Create a new Postgres container, random port is assigned:
<img width="260" alt="random-port2" src="https://cloud.githubusercontent.com/assets/3965324/17422694/1e0ae0f0-5a69-11e6-9aba-921471588bbd.png">
4. Try to assign the port of 5432 results in an error:
<img width="818" alt="collision" src="https://cloud.githubusercontent.com/assets/3965324/17422718/4946c022-5a69-11e6-9a2b-b491660fc58e.png">


Providing us with _exact_ repeatable steps, with the environment that you're in and with screenshots (as I did above) would help me understand the issue you're having. You did none of this until your last comment.

**Comment by pslootweg** [comment] 2016-08-11 17:05
I can show that you CAN:

One container with Postgres:latest mapped to 5432:5432

<img width="1072" alt="screen shot 2016-08-11 at 17 54 47" src="https://cloud.githubusercontent.com/assets/18535779/17597343/40403fd8-5fed-11e6-9c58-9763602b6425.png">

and one with Postgres:9.1.13 mapped to 5432:5432

<img width="1064" alt="screen shot 2016-08-11 at 17 55 16" src="https://cloud.githubusercontent.com/assets/18535779/17597364/5adf57fc-5fed-11e6-80a9-f0dc7d7d0613.png">

In fact, there is a 3rd mapped to 5432:5432 - but that's irrelevant.

If I now try to start the 2nd instance, *no error message is shown*

<img width="1067" alt="screen shot 2016-08-11 at 18 01 23" src="https://cloud.githubusercontent.com/assets/18535779/17597452/bf811902-5fed-11e6-9019-1028f38ed941.png">

If I then navigate to Settings and click on 'Save'

<img width="1067" alt="screen shot 2016-08-11 at 18 01 23" src="https://cloud.githubusercontent.com/assets/18535779/17597503/fb7b3b5e-5fed-11e6-8645-7daeceb96cf9.png">

then when I navigate back to 'Home' it shows

<img width="1066" alt="screen shot 2016-08-11 at 18 04 30" src="https://cloud.githubusercontent.com/assets/18535779/17597526/16ceab84-5fee-11e6-96d5-7c85d67d13fa.png">

As invited on that dialog, I filed a ticket.

**Comment by pslootweg** [comment] 2016-08-11 17:14
It only seems to detect a port conflict if there is another container running on that port. Otherwise I can add a new container and assign it to port 5432

<img width="716" alt="screen shot 2016-08-11 at 18 11 04" src="https://cloud.githubusercontent.com/assets/18535779/17597771/4763b4dc-5fef-11e6-89ed-47e22ed0a90c.png">

My original issue that that there was a postgres instance running *outside* Docker, and the port conflict with *that* was not detected, and I got the error scenario I demonstrated in my previous post.

**Comment by FrenchBen** [comment] 2016-08-11 22:10
That's correct - Running containers are the only ones that tie a port; non-running containers wasn't part of the original discussion. 

When you hit `save` we don't dynamically update the container, we re-created it, which then triggers the `500 error` that you're seeing, granted the error should've been more verbosed than `[object Object]`.

In the latest version you will see something like:
```
(HTTP code 500) server error - driver failed programming external connectivity on endpoint postgres (4e5c8753bcc5b37d4613755a0d1832571da819757f076797dce51417453d2db3): Bind for 0.0.0.0:5432 failed: port is already allocated
```

I'm not sure if there is a good way to handle this; technically a non-running container should not prevent you from creating another container and using that port.

**Closed by FrenchBen** 2016-08-11 22:10 UTC
