### ISSUE TITLE
Can't run any Mac releases after 0.10.4, Mac OS X says "app is damaged"

### ISSUE THREAD

**Issue by dmay** [docker/kitematic#1785] opened 2016-06-28 18:25 UTC
### Expected behavior
Application runs.

### Actual behavior
Mac OS shows message box
“Kitematic (Beta).app” is damaged and can’t be opened. You should move it to the Trash.
and offers to move app to Trash

### Information about the Issue
I've tried 0.12.0, 0.10.5 and 0.10.4 from https://github.com/docker/kitematic/releases , *-Mac.zip
Tried to re-download few times, tried built-in unarchiver, 3rd party archive manager, WinRAR in Windows VM. Same result.

OS X El Capitan, 10.11.3

### Steps to reproduce the behavior

  1. Download https://github.com/docker/kitematic/releases/download/v0.12.0/Kitematic-0.12.0-Mac.zip from https://github.com/docker/kitematic/releases
  2. Unpack it to get "Kitematic (Beta).app"
  3. (optional, doesn't affect result) Move app to Applications
  4. Double click app OR Right click - Open OR Launch from Spotlight
  5. OS shows "app is damaged" window

**Comment by FrenchBen** [comment] 2016-06-28 23:36
This is a duplicate of a previous issue.
https://github.com/docker/kitematic/issues/1637#issuecomment-210924052

For unknown reason, OSX attrs are added to certain downloads, see:
http://apple.stackexchange.com/questions/129966/files-wrongly-considered-as-damaged-in-encfs-volume


To solve it, run:
```
xattr -rc /Applications/Kitematic\ \(Beta\).app
```
 A reboot and re-download can show a clean download as well.

**Closed by FrenchBen** 2016-06-28 23:36 UTC
