### ISSUE TITLE
failed to register layer: Untar re-exec error: exit status 1: output: no such file or directory

### ISSUE THREAD

**Issue by s1rc0** [docker/kitematic#1467] opened 2016-02-12 21:03 UTC
Hi,

Getting "failed to register layer: Untar re-exec error: exit status 1: output: no such file or directory" when trying to load jenkins official image via Kitematic 

OS: Win10

**Comment by alexandrev** [comment] 2016-02-14 11:37
I cannot reproduce this error on Windows 10. Maybe an error with the network during the creation of the container? Could you try again? Beucase I have no problem today downloading the image from the  Kitematic recommended repos:

![image](https://cloud.githubusercontent.com/assets/947041/13033473/bdf06812-d317-11e5-912d-8ee9aadf04cc.png)

**Comment by s1rc0** [comment] 2016-02-14 13:48
it will not be repeated any more. It happened only once at startup of the first container

**Comment by alexandrev** [comment] 2016-02-14 14:29
So, it is seems a temporary problem regarding probably to your network
connection or anything related to the docker daemon but no kitematic.

**Comment by FrenchBen** [comment] 2016-02-15 22:46
Closing until steps to reproduce can be provided.

**Closed by FrenchBen** 2016-02-15 22:46 UTC

**Comment by S3curityPlu5** [comment] 2017-02-21 20:37
I get this error only on windows server 2016, not on windows 10.  may be reproducible on a windows server core 2016 host, that does not have virtual machine extensions exposed. Just fyi

**Comment by FrenchBen** [comment] 2017-02-22 01:24
@S3curityPlu5 Are you trying to use Linux containers or Windows containers?

**Comment by S3curityPlu5** [comment] 2017-02-22 13:09
Linux containers, but I think I solved the problem, it was an older version that was on this servercore server2016 VM.  What is the correct way to update docker on windows server core ? there is not really a good way to uninstall programs, so I just re-installed docker using find-package install-package, I've been able to get the windows server containers to work, it's the linux containers giving me problems.
