### ISSUE TITLE
Feature Request: Ability to start a privileged container

### ISSUE THREAD

**Issue by robtec** [docker/kitematic#269] opened 2015-03-13 21:17 UTC
Would be cool to do this using the UI, if its possible to enable USBs via the Virtual Box API, I'm sure its not as easy at it looks :smile:

**Comment by mchiang0610** [comment] 2015-03-13 21:21
Thanks for providing feedback.

**Comment by robtec** [comment] 2015-03-13 21:29
No problem :smile: 

I must say its a pretty slick UI, is most of the markup just javascript?

**Comment by mchiang0610** [comment] 2015-03-13 21:30
Yes. :) :+1:

**Comment by robtec** [comment] 2015-03-13 21:32
Do you have an IRC channel? :computer:

**Comment by mchiang0610** [comment] 2015-03-13 22:47
@robtec Not at the moment.

**Comment by robtec** [comment] 2015-03-13 22:54
@mchiang0610 no problem, just setting up the dev environment, think I'm missing an API key somewhere, getting this error
![screen shot 2015-03-13 at 22 52 36](https://cloud.githubusercontent.com/assets/8657653/6648603/cd5f2278-c9d3-11e4-8e99-a3da3887e05b.png)

**Comment by jeffdm** [comment] 2015-03-14 22:24
Thanks - can you pull up the logs? You can open the debugger with `cmd+alt+I`.

**Comment by robtec** [comment] 2015-03-14 22:45
Hope this helps :+1: 

![screen shot 2015-03-14 at 22 44 21](https://cloud.githubusercontent.com/assets/8657653/6653905/c7dd4d0c-ca9b-11e4-9a0b-11ebb6590f45.png)

**Comment by jeffdm** [comment] 2015-03-14 22:52
What's the output of `docker-machine ls` on a regular Mac OS X Terminal?

Thanks

**Comment by robtec** [comment] 2015-03-14 23:03
```bash
robpowell@Robs-MacBook-Pro ~/D/w/kitematic> docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev    *        virtualbox   Running   tcp://192.168.99.101:2376   
```

Note I am setting up the kitematic development environment, from the instructions in the `README`

I have the standalone app installed too which works fine, just wondering where does the development version need an API key? docker hub maybe?

**Comment by jeffdm** [comment] 2015-03-14 23:13
No API key required (sorry about the misleading info msg in the console).

This error is caused by our docker-machine bindings.

Last thing, can you try: `ls ./resources`?

Are the `docker` and `docker-machine` binaries correctly downloaded in the `resources` dir? I just pushed a fix for this, so it's most likely the problem.

Thanks!

**Comment by robtec** [comment] 2015-03-14 23:37
```bash
robpowell@Robs-MacBook-Pro ~/D/w/kitematic> ls ./resources/
macsudo  terminal
```

Pulled the latest and ran `npm install` then `npm start`, its working fine now :+1:

**Comment by jeffdm** [comment] 2015-03-14 23:43
Good to know!

**Comment by wzymaster** [comment] 2015-10-02 18:16
This feature is added in the latest Kitematic ?

**Comment by matteocrippa** [comment] 2016-04-25 15:13
Any news about this? It would be very cool eg. for swift you are forced to run it in privileged mode to have full features working ( https://github.com/lxcid/docker-swift )

**Closed** 2016-05-24 00:15 UTC
Labels: feature
